name: Terraform-EKS-CICD

on:
  push:
    branches: [ "main" ]

  pull_request:
    branches: [ "main" ]

env:
  TF_CLOUD_ORGANIZATION: poc_check1
  TF_WORKSPACE: eks-prod

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:

      # -------------------------------
      # Checkout repo
      # -------------------------------
      - name: Checkout repository
        uses: actions/checkout@v4

      # -------------------------------
      # Install Terraform
      # -------------------------------
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # -------------------------------
      # Write Terraform Cloud token
      # -------------------------------
      - name: Configure Terraform Cloud token manually
        run: |
          mkdir -p $HOME/.terraform.d
          cat > $HOME/.terraform.d/credentials.tfrc.json <<EOF
          {
            "credentials": {
              "app.terraform.io": {
                "token": "${{ secrets.TF_API_TOKEN }}"
              }
            }
          }
          EOF

      # -------------------------------
      # Debug token + HOME
      # -------------------------------
      - name: Debug Terraform auth
        run: |
          echo "HOME=$HOME"
          ls -la $HOME/.terraform.d || true
          cat $HOME/.terraform.d/credentials.tfrc.json || true

      # -------------------------------
      # Force Terraform to read config
      # -------------------------------
      - name: Force Terraform CLI config
        run: |
          echo "TF_CLI_CONFIG_FILE=$HOME/.terraform.d/credentials.tfrc.json" >> $GITHUB_ENV

      # -------------------------------
      # Terraform Init
      # -------------------------------
      - name: Terraform Init
        run: terraform init

      # -------------------------------
      # Terraform checks
      # -------------------------------
      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

      # -------------------------------
      # Apply only on push to main
      # -------------------------------
      - name: Terraform Apply (only on main push)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve
